excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- iOS-Template/API.swift
- vendor

line_length: 300

disabled_rules:
- multiple_closures_with_trailing_closure

identifier_name:
  allowed_symbols: "_"
