name: SwiftLint
on:
  push:
    branches:
      - feature/fastlane_integration
    paths:

jobs:
  SwiftLint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        run: fastlane customLane

