name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
    - name: Install dependencies
      run: sh ./bootstrap.sh
    - name: Build and test
      run: bundle exec fastlane beta
