name: Swift

on:
  push:
    branches: [ master feature/mvvm-coordinator ]
  pull_request:
    branches: [ master feature/mvvm-coordinator ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
